
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bidnqcafzochmwrevwhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZG5xY2Fmem9jaG13cmV2d2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Mjc1OTksImV4cCI6MjA2MzAwMzU5OX0.WRjlnipWyvWOEGPG_ywy_GbHOlJ_IIN3Z-JX0XjXXio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
