
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xueziitmykcjdmybfckc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1ZXppaXRteWtjamRteWJmY2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDUzMjEsImV4cCI6MjA2Njc4MTMyMX0.q12sDpIMhywcHqT-kxjHSJ79wKJ9vgH16yS2XKO3IxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
