// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kowibkflehnvmhhdxhpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvd2lia2ZsZWhudm1oaGR4aHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Njg5MDIsImV4cCI6MjA2MzI0NDkwMn0.XeLIehR-KeG-V1b-G2R4A5-ysOKneOE34jxb_0zXGHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);